seed: 1234567
usewandb: true

dataloader:
  batch_size: 16
  n_workers: 20

  dataset_dir: dataset/2_gensdf_dataset
  samples_per_mesh: 16000
  pc_size: 4096
  uniform_sample_ratio: 0.3
  cache_size: 2195

SdfModelSpecs:
  tanh_act: False
  skip_connection: True
  hidden_dim: 512
  latent_dim: 256
  pn_hidden_dim: 128
  num_layers: 9

evaluation:
  max_batch: 262144  # 2^18
  resolution: 256
  count: 50
  freq: 100


eval_mesh_output_path: logs/gensdf/meshes

num_epochs: 1000001
kld_weight: 0.01
latent_std: 0.25
latent_dim: 256 # original 786 = SdfModelSpecs.latent_dim * 3

checkpoint_output: checkpoints/gensdf
save_checkpoint_freq: 50 # epcho

sdf_lr: 0.00015