output_dataset_path: dataset/2_onet_dataset
latent_code_output_path: dataset/3_generation_latent_code
checkpoint_output: checkpoints/onet
check_point_path: checkpoints/onet
check_point_filename: null
random_seed: love ytq.
shape_description_path: dataset/4_screenshot_description
transformers_name: google-t5/t5-base
pretrained_model_cache_dir: cache


host: localhost
port: 6379
db: 0
raw_shape_info_paths: dataset/1_preprocessed_info

action:
  - gen_latent_code
  - push_to_redis