train_by_sdf: true
sdf_ratio: 0.1

optimizer:
  betas: [0.9, 0.98]
  eps: 1.0e-9
  scheduler_factor: 0.17
  scheduler_warmup: 15

seed: love ytq.
batch_size: 14
total_epoch: 10000
emb_sigma: 0.2
dataset_root_path: dataset/2_onet_sdf_dataset
checkpoint_output: checkpoints/onet_sdf
z_dim: 128
