train_by_sdf: false

optimizer:
  use_warmup: false
  lr: 1.5e-3
  betas: [0.9, 0.98]
  eps: 1.0e-9
  scheduler_factor: 0.25
  scheduler_warmup: 40

sdf_ratio: 0.6

eval_mesh_output_path: logs/onet_occ/eval_mesh

seed: love ytq.
batch_size: 8
total_epoch: 10000

emb_sigma: 0.7

dataset_root_path: dataset/2_onet_occ_dataset
checkpoint_output: checkpoints/onet_occ
z_dim: 256
