use_v1_dataset: false

sdf_dataset: true

optimizer:
  betas: [0.9, 0.98]
  eps: 1.0e-9
  scheduler_factor: 0.17
  scheduler_warmup: 15

sdf_ratio: 0.1

seed: love ytq.
batch_size: 10
total_epoch: 10000
train_ratio: 1
emb_sigma: 0.35
dataset_root_path: dataset/2_onet_sdf_dataset
checkpoint_output: checkpoints/onet_sdf
z_dim: 128
selected_categories:
 - '*'
  # - USB
  # - Chair
  # - Door
  # - StorageFurniture
  # - Toilet
