use_v1_dataset: false

seed: love ytq.
batch_size: 8
lr_rate: 1.509122003e-3
total_epoch: 10000
train_ratio: 0.9
emb_sigma: 0.3
dataset_root_path: dataset/2_onet_v2_dataset
checkpoint_output: checkpoints/onet
z_dim: 128
leaky: 0.05
optimizer: adam
selected_categories:
 - USB
#  - Chair
#  - Door
#  - StorageFurniture
#  - Toilet