random_seed: love ytq forever
device: null

action:
  type: eval
  args:
    ckpt_filepath: checkpoints/transformer/native-00900.ckpt
    eval_output_path: logs/eval_output
    equal_part_threshold: 0.5


######### For evaluation ONLY, the paramerters for latentcode decoder.
n_latent_code_validation_samples: 10000
latent_decoder:
  type: null
  ckpt_path:
######### END

# Dataset & Dataloader config
dataset:
  type: redis_parallel
  args:
    db: 0
    port: 6379
    host: localhost
    fix_length: 5

dataloader:
  args:
    batch_size: 1
    num_workers: 1
    shuffle: False

part_structure:
  non_latent_info:
    origin: 3
    direction: 3
    bounds: 6
    tran: 3
    limit: 4
  latent_info:
    latent: 128
  other_info:
    dec_samplepoint: [50000, 3]
    dec_occ: 50000
