action:
  type: train
  args:
    epochs: 1000
    save_dir: 'checkpoints/native-{epoch:05d}.pt'
    lr: 1e-4

tokenlizer:
  type: 'MLPTokenizer'
  args:
    d_model: 256
    hidden_dim: 512
    leaky_relu: 0.01

position_embedding:
  type: 'NonePositionEmbedding'
  args: null

dataset:
  type: 'redis'
  args:
    host: 'localhost'
    port: 6379
    db: 0

dataloader:
  args:
    batch_size: 32
    num_workers: 4

decoder:
  type: NativeDecoder
  type:
    n_head: 8
    n_layer: 6
    d_model: 256
