action:
  type: train
  args:
    n_epoch: 1000
    ckpt_save_name: checkpoints/native-{epoch:05d}.pt
    lr: 1e-5
    optimizer: adam

usewandb: true
random_seed: love ytq forever

part_structure:
  non_latent_info:
    origin: 3
    direction: 3
    bounds: 6
    tran: 3
    limit: 4
  latent_info:
    latent: 128

tokenizer:
  type: NativeMLPTokenizer
  args:
    part_hidden_dim: 512
    hidden_dim: 512
    leaky_relu: 0.01
    drop_out: 0.1

dataset:
  type: redis
  args:
    db: 0
    host: localhost
    port: 6379
    fix_length: 5

dataloader:
  args:
    batch_size: 8
    num_workers: 4
    shuffle: true

decoder:
  type: NativeDecoder
  args:
    n_head: 8
    n_layer: 6
    d_model: 512
    max_len: 128
    dropout: 0.05
    expanded_d_model: 2048
    latent_code_dim: 128
    vocab_size: 1048576 # >>> 2048 * 512


feedforward: # TODO: try KAN.
  args:
    hidden_dim: 2048
    dropout: 0.1


