action:
  type: train
  args:
    n_epoch: 1000
    ckpt_save_name: checkpoints/native-{epoch:05d}.pt
    lr: 1e-4
    optimizer: adam

usewandb: false

tokenizer:
  type: NativeMLPTokenizer
  args:
    hidden_dim: 256
    leaky_relu: 0.01
    drop_out: 0.1

dataset:
  type: redis
  args:
    host: localhost
    port: 6379
    db: 0
    fix_length: 5

dataloader:
  args:
    batch_size: 3
    num_workers: 4

decoder:
  type: NativeDecoder
  args:
    n_head: 8
    n_layer: 6
    d_model: 512
    max_len: 128
    dropout: 0.05
    expanded_d_model: 2048
    latent_code_dim: 128

feedforward: # TODO: try KAN.
  args:
    hidden_dim: 2048
    dropout: 0.1


